name: Release Packaged Script
on:
  push:
    tags:
      - "*"
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: pip install requests

      - name: Create executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.9"
          spec: "DeadlockTC.py"
          upload_exe_with_name: "DeadlockTC"
          options: --onefile, -i project8.ico

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $tag = $env:GITHUB_REF -replace 'refs/tags/', ''
          gh release create $tag `
            --title="$tag" `
            --draft `
            dist/DeadlockTC.exe
        shell: pwsh
